---
title: Setup
author: "Roopa Krithivasan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Steps: 

### 1. Create funtion

After a number of failed attempts, I decided that it works best to create your function first in a blank script, and save it with the name of the function. Save it somewhere you can find it later. 

So, I created, the hagfish function, which is this:

```
hagfish_function <- function (love = T){
  if (love == T){
    print("hagfish need love too")
  }
  else {print ("hagfish are weird")
  }
}
``` 

and saved it as "hagfish_function.R"

### 2. Create package

Use new project > new directory > new package to create a package. Make sure to tick "git"
This package is called rka1k. Eleventh time's the charm. 

Note: it will by default create a "hello" function if you don't tell it to populate the package with an existing function. 

### 3. Save function to package

save a copy of hagfish_function.R to the R folder in rka1k,

### 4. Document the function

open hagfish_function.R in the Rstudio project for the package (rka1k.Rproj).
Add documentation text, that'll be recognized by the "document" function in devtools. I basically used the same text as in the tutorial, with minor edits. So the script now looked like this:

```
#' A hagfish function
#'
#' This function allows you to express your love of hagfish.
#' @param love Do you love hagfish? Defaults to TRUE.
#' @keywords hagfish
#' @export
#' @examples
#' hagfish_function()

hagfish_function <- function (love = T){
  if (love == T){
    print("hagfish need love too")
  }
  else {print ("hagfish are weird")
  }
}

```
Create the documentation:

make sure you have the devtools and roxygen2 packages installed and loaded

```
library(devtools)
library(roxygen2)
```

Set working directory to rka1k (if it's not already there), then

```
document()
```

Check to make sure this worked:

```
?hagfish_function
```

This should pull up the documentation in the help tab.


### 5. Build the package

When I created a package using the built-in RStudio options, the NAMESPACE file doesn't contain the right information, so the package isn't recognized as a package if you try to install it. so, I needed to go through the following steps:

- first, go into project options, click build tools (left side of the box), turn on "use devtools..." and "generate documentation...", making sure that all of the boxes within "generate documentation..." are clicked on. 
- delete the namespace file from within the rka1k folder
- in the build menu (tab next to "Environment" and "History" in the RStudio window), click "build and reload"
- this should create a functional NAMESPACE file, and confirm that the package works


### 6. Create repository and commit 

in the git tab, select all of the options under "staged" 
click commit, add a comment. hit commit again. this should update the repo
In github, create a new repository called "rka1k"
Open Shell within RStudio, add the origin, and push what you ahve so far as the master

git remote add origin git@github.com:roopakrithi/rka1k.git
git push -u origin master

for any subsequent commits to github, 
git push

### check to see if everthing worked

install the package from github, and see if the function works:

```
devtools::install_github("roopakrithi/rka1h")
hagfish_function(love = T)
hagfish_function(love = F)
?hagfish_function
```



## all the things I messed up

- creating the package using "create" seems to mess things up if I want to create a git Repo.I still haven't figured out why but in the meantime I'll be creating packages in the way outmined above
- Make sure to re-create the NAMESPACE file using build. 
- if creating packages using the RStudio "new project" method, make sure that Project options > build tools has all of the devtools and roxygen2 options turned on
